# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 20:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rbot', '0005_auto_20170325_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneCall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('call2_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('from_number', models.CharField(blank=True, max_length=255, null=True)),
                ('to_number', models.CharField(blank=True, max_length=255, null=True)),
                ('requested', models.DateTimeField(blank=True, null=True)),
                ('connected', models.DateTimeField(blank=True, null=True)),
                ('completed', models.DateTimeField(blank=True, null=True)),
                ('completed2', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('duration2', models.IntegerField(blank=True, null=True)),
                ('call_status', models.CharField(blank=True, max_length=255, null=True)),
                ('call_status2', models.CharField(blank=True, max_length=255, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbot.Conversation')),
            ],
        ),
    ]
