# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='stage',
            field=models.CharField(blank=True, choices=[(b'welcome', b'Welcome')], db_index=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='status',
            field=models.CharField(choices=[(b'a', b'Active'), (b'c', b'Completed'), (b'f', b'Abandoned')], db_index=True, default=b'a', max_length=1),
        ),
    ]
