# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 18:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ridings', '__first__'),
        ('rbot', '0002_auto_20170325_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='representative_email',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='representative_fax',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='representative_name',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='representative_phone',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='riding_id',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='riding_name',
        ),
        migrations.AddField(
            model_name='conversation',
            name='riding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ridings.Riding'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='stage',
            field=models.CharField(blank=True, choices=[(b'welcome', b'Welcome'), (b'postal_code', b'PostalCode')], db_index=True, max_length=15, null=True),
        ),
    ]
