# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbot', '0003_auto_20170325_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='stage',
            field=models.CharField(blank=True, choices=[('welcome', 'Welcome'), ('postal_code', 'PostalCode')], db_index=True, max_length=25, null=True),
        ),
    ]
