# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 22:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbot', '0005_auto_20170325_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='message',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='topic',
        ),
    ]
