# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 04:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbot', '0007_smsmessage_media_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='topic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
