# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 22:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rbot', '0006_auto_20170325_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='WrittenMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent', models.DateTimeField(blank=True, null=True)),
                ('topic', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('png', models.BinaryField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbot.Conversation')),
            ],
        ),
    ]
